<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <RootNamespace>CP4</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.40" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CP4.Application\CP4.Application.csproj" />
      <ProjectReference Include="..\CP4.Infrastructure\CP4.Infrastructure.csproj" />
    </ItemGroup>

</Project>
